#!/usr/bin/env bash
#
# Clear out the old overlays dirs to 
# free up room on backups, and prepare for
# moving overlays to a single location
#
home=~Johnny/coLab
group=Johnny
group=Catharsis

cd $home
starting=$(du -s )

for group in Test SBP Johnny Catharsis
do
	if ! cd $home/Group/$group/Page
	then
		echo "$0: bad start"
		exit 1
	fi
	
	# 
	for i in *
	do
		if [ ! -f $i/data ]
		then
			echo $i is not a coLab page dir...
			continue
		fi
		unset page_type
		eval $(grep page_type $i/data)
		if [ "$page_type" = html5 ] 
		then
			echo $i $page_type
			rm -rfv $i/coLab_local/Overlays
		else
			echo "-------->" $i $page_type
		fi
	done
done
cd $home
ending=$(du -s)

echo "Starting size: $starting"
echo "Ending size:   $ending"
