#!/usr/bin/env sh
#
# intial take a setting up a site - basically create the
# dir, add it to Site.List and provide a template data file.
# 
name="$1"

#set -x
if [ -z "$name" ]
then
        echo "$0: usage: newDomain <domain>"
        exit 1
fi




if [ -d "../Domains/$name" ]
then
        echo "$0: $name already exists..."
        echo "OK?"
        read ans
        if [ "$ans" != y ]
        then
                echo I was looking for: y
                exit 0
        fi
fi

if grep $name "../Domains/Domain.List"  >/dev/null
then
        echo "$0: $i is in Domain.List file"
else
	echo $name >>../Domains/Domain.List
fi

mkdir -pv "../Domains/$name"

data="../Domains/$name/data"

if [ ! -f "$data" ]
then
	cat <<-EOF >"$data"
	name="$name"
	desc_title=""   # descriptive / short
	fun_title=""    # have fun

	create="$(date "+%Y-%m-%d %H:%M:%S")"
	update="$(date "+%Y-%m-%d %H:%M:%S")"
	EOF
fi

