#!/usr/bin/env sh
#
# intial take a setting up a site - basically create the
# dir, add it to Site.List and provide a template data file.
# 
name="$1"

#set -x
if [ -z "$name" ]
then
        echo "$0: usage: newPage <page>"
        exit 1
fi



pagehome="~/dev/coLab/Group/Catharsis/Page/$name"

if [ -d "~/dev/coLab//$name" ]
then
        echo "$0: $name already exists..."
        echo "OK?"
        read ans
        if [ "$ans" != y ]
        then
                echo I was looking for: y
                exit 0
        fi
fi


mkdir -pv $pagehome

data="$pagehome/data"

if [ ! -f "$data" ]
then
	cat <<-EOF >"$data"
	name="$name"
	desc_title=""   # descriptive / short
	fun_title=""    # have fun

	create="$(date "+%Y-%m-%d %H:%M:%S")"
	update="$(date "+%Y-%m-%d %H:%M:%S")"
	EOF
fi

