#!/usr/bin/env sh
#
# rebuild the menu and link files...
# Temporary - need to move this to Python and/or PHP
#

home=~/dev/coLab

if ! cd $home
then
	echo "$0: cannot cd to $home"
	exit 1
fi

#
# For now we just build the left menu
#
leftside="$home/Shared/sidebar_l.html"

if  ! touch $leftside 
then
	echo "$0: cannot access file: $leftside" >&2
	exit 1
fi

echo "$0: Updating $leftside"

cat <<-EOF >$leftside
<!--
	Shared left side bar, generated by $0 on $(date)
-->

<div class="sidebar_l">
<h4>Recent Updates</h4>
<ul>
EOF

sitelist="$home/Sites/Site.List"

if  ! touch $sitelist
then
	echo "$0: cannot access file: $sitelist" >&2
	exit 1
fi

#
# return the 'n' most recent (non-comment) lines - last n lines
# in the file, in reverse order
n=5
recentlist=$(grep -v "^#" $sitelist | tail -n $n -r )
for piece in $recentlist
do
	data="$home/Sites/$piece/data"
	if [ ! -f "$data" ]
	then
		echo "$0: Warning: no such file: $data"
		desc_title="$piece"
	fi

	source $data

	if [ -z "$fun_title" ]
	then
		fun_title="$desc_title"
	fi

	if [ -z "$create" ]
	then
		create="(unknown)"
	fi

	if [ -z "$update" ]
	then
		update="$create"
	fi
	#
	# Now we should be ready to emit a list item link...
	cat <<-EOF >>$leftside
	<li><a href="../Sites/$piece/" title="$fun_title">$desc_title</a><br><i>$update</i></li>
	EOF

done
cat <<-EOF >>$leftside
</li>

EOF

cat <<-EOF >>$leftside
</div>
EOF
