#!/usr/bin/env sh
#
# I'm just looking for some (data)  touch...
#
cd ~/coLab/Group/
glist="*"
glist="Johnny"
#glist="SBP"
#glist="Catharsis"
#glist="Johnny SBP Catharsis Test"
for group in $glist
do
	(
	cd $group
	for i in $(find . -name data)
	do 
		echo $i
		touch $i
	done
	)

done
