<tr><td><h3>JDJ-V Assmbly4</h3>
<h4>JDJ-V Assmbly 4 Yr Wel.cm</h4>

About time for a new assembly...
<p>
From the upper left to the lower right, there are:
<ul>
 <li>Intro<br>
 new EQ
 <li>Walk on the Beach<br>
 Pruned flutes reunited with the rest
 <li>Secluded Cove<hr></td></tr>
<tr><td><h3>Initial Flute Prune</h3>
<h4>A Big, Heaping Bowl of Pruned Flutes!</h4>

<i>(I know, not again - but this was fun!)</i>
<p>
In prepping for a new assembly test, 
I decided to do a one-pass flute prune.  Still a bit 
busy in spots, but ducking a few outliers - which you ca<hr></td></tr>
<tr><td><h3>Cove String Solo</h3>
<h4>Cove String Solo</h4>
In search of something "new" I could post, I revisited Cove and
started looking for string sounds.   A dozen or so string patches in I 
had several in mind,
perhaps merged together carefully, they mig<hr></td></tr>
<tr><td><h3>Cove: String, Piano</h3>
<h4>Widening Cove, Distant Flute</h4>
Here's the previous "string" version of Cove, with only 
	the piano mics added.   The flute is just
	audible, sometimes more than just,  but I actually like it in spots.   
	We can add in more or less<hr></td></tr>
<tr><td><h3>Beach, next phase</h3>
<h4>Ham and Eggs on the Beach</h4>
This little tool is getting close to useful.   Here is Beach with
        the piano doubled on a rhodes, and a few other rhythmical friends.  Also,
        all five flutes are on board,   Pretty much <hr></td></tr>
<tr><td><h3>Second Turn with Drum, Bass, etc.</h3>
<h4>Second Try with Turn</h4>
This is my first attempt at automating a large portion of the web page generation.
I'm typing these comments as the other script builds the couple thousand images.
This is the version of Second Turn (<hr></td></tr>
<tr><td><h3>ShortIntro Test</h3>
<h4>From before the beginning...</h4>
This is mostly a test to see if my scripting can create
	the html index file in place with a pre-existing web site.
	<p>
	This is the first half of the short intro with the second half 
	ending splice<hr></td></tr>
