<!-- Start: .../coLab/Resources/include/page/banner.inc -->
<div id="banner" > <! start of banner>
	<table width=80% border=0 cellpadding=0 class="banner_txt">
	  <td align="center" ><a href="<?php echo $groupURL?>/index.shtml" title="Always a nice place to go...">Home</a></td>

	  <td align="center" ><a href="<?php echo $groupURL?>/Shared/WhatsNew/index.shtml" title="The place to be, if you want to be somewhere else.">What's&nbsp;New</a></td>
	  <td align="center" ><a href="<?php echo $groupURL?>/Shared/Nav/index.shtml" title="How to get to where you need go.">Nav</a></td>
	  <td align="center" ><a href="<?php echo $groupURL?>/Shared/Archive/index.shtml" title="What have we been up to...">Archive</a></td>
	  <td align="center" ><a href="<?php echo $groupURL?>/Shared/Help/index.shtml" title="Hopefully, the help you need.">Help</a></td>
	</tr></table>
<br>
</div>	<! end of banner>
<!-- End: .../coLab/Resources/include/page/banner.inc -->
