<!-- /Volumes/iMac 2TB/Software/coLab/Resources/include/page/content.inc -->
<p>
	<! Start links...>
	<!--#include virtual="links.html" -->
	<! ...end links.>
	<div class="maintext">
	<br>
	<!-- gittin' a little tricky w/alignment... -->
	<table border=0 cellpadding=0 width=100%><tr>
	<td valign=top><img src="Header.png" align=left alt="<?php echo $desc_title; ?>"><br clear=all>
	<i>Created: <?php echo $createtime ?> </i></td>
	<td valign=center align=right><b>Duration: <?php echo $duration; ?> </b></td></tr></table>
	<p><font color=a0b0c0><?php echo $description; ?><p>
