<!-- Start: .../coLab/Resources/include/page/content.inc -->
<div id="toplinkbar">	
	<! Start links...>
	<?php virtual ("links.html"); ?>
	<! ...end links.>
</div>	<!-- end toplinkbar -->
<br>
	<div id="maintext">

	<!-- gittin' a little tricky w/alignment... -->
	<table border=0 cellpadding=0 width=100%><tr>
	<td valign=top><img src="Header.png" align=left alt="<?php echo $desc_title; ?>"><br clear=all>
	<i>Created: <?php echo $createtime ?> </i></td>
	<td valign=center align=right><b>Duration: <?php echo $duration; ?> </b></td></tr></table>
	</td></tr></table>
	<p><?php echo $description; ?></p>
<!-- End: .../coLab/Resources/include/page/content.inc -->
