<!DOCTYPE html>
<!-- Start: /coLab/Resources/include/page/head.inc -->
<html>
    <head><title><?php echo $fun_title ?></title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<!-- css -->
	<link rel="stylesheet" type="text/css" href="/coLab/Resources/Style_Default.css">
	<!link rel="stylesheet" type="text/css" href="/coLab/Resources/bootstrap/css/bootstrap.css">
	<!link rel="stylesheet" type="text/css" href="/coLab/Resources/context.bootstrap.css">
	<link rel="stylesheet" type="text/css" href="/coLab/Resources/context.standalone.css">
	<link rel="shortcut icon" href="/coLab/Resources/CoLab_Logo2D.png">

	<!-- javascript and friends -->
	<! Good old jQuery >
	<script type="text/javascript" src="/coLab/Resources/jquery-1.11.1.min.js"></script>
	<! Our main javascript to drive the video - and most everything else >
	<script type= "text/javascript" src="/coLab/Resources/video_engine.js"></script>
	<! the ContextJS package for working context menus >
	<script type="text/javascript" src="/coLab/Resources/context.js"></script>
    </head>
<!-- End: /coLab/Resources/include/page/head.inc -->
