<!DOCTYPE html>
<!-- /Volumes/iMac 2TB/Software/coLab/Resources/include/page/head.inc -->
<html>
	<head><title><?php echo $fun_title ?></title>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="/coLab/Resources/Style_VidAuto.css">
	<!link rel="stylesheet" type="text/css" href="/coLab/Resources/bootstrap/css/bootstrap.css">
	<!link rel="stylesheet" type="text/css" href="/coLab/Resources/context.bootstrap.css">
	<link rel="stylesheet" type="text/css" href="/coLab/Resources/context.standalone.css">
	<link rel="shortcut icon" href="/coLab/Resources/CoLab_Logo2D.png">
